### ISSUE TITLE
it seems it remembers a mode from previous world

### ISSUE THREAD

**Issue by tompok76** [Exxarion/WorldGM#12]
Hello,
idk to thank you for a cool plugin. Thks
But on my linux php5.6, mcpe bleeding 43 this plugin dont change set mode and remember it from previous world. For an example:
I am in world cmode, i go to world smode and still get cmode, i return to world with cmode and now i get smode. 
Thank you for your plugin ( I am not abble to create it ) and I am waitting for advice or upgr.
Have a nice day, Tom

**Comment by Exxarion** [comment]
Fixed in v9.0
