### ISSUE TITLE
1.6?

### ISSUE THREAD

**Issue by MilkoIvanov** [Exxarion/WorldGM#13]
Is the plugin getting update soon?

**Comment by Exxarion** [comment]
I have not planned on it yet. I might update it, though.

**Comment by MilkoIvanov** [comment]
Thanks I think a lot of people are in need of it too

**Comment by Exxarion** [comment]
https://github.com/Exxarion/WorldGM/releases/tag/v9.0

The plugin now supports the latest pocketmine builds, and now works properly with them.
