### ISSUE TITLE
Bug Gamemode for worlds

### ISSUE THREAD

**Issue by matcracker** [Exxarion/WorldGM#5]
Hi, I found a lot of bug in your plugin :(

1)When I use /wgm set 0/1/2 nameworld it give me the message " [WorldGM] That world does not exist."
2)When player in creative mode go into the world in survival mode don't change the gamemode and he remains in creative.

Please, Fix all the bugs! Thank You! :+1: :)

- matcracker

**Comment by Exxarion** [comment]
1) For weird purposes, you cannot do the world parameter. You must be in the world to set the gamemode. So basically, goto the world you want to set, do /wgm set 0/1/2
2) This is being worked on. Trying to fix this for WorldGM 4.0

Thanks

**Comment by matcracker** [comment]
OK! Good job man! :+1:

**Comment by Exxarion** [comment]
Everything is fixed

**Comment by Thomasfda** [comment]
Hi, the bug is not fix ! I have "That world does not exist"

**Comment by Exxarion** [comment]
Use 4.0

https://github.com/Exxarion/WorldGM/releases/tag/v4.0

This update is not released on Pocketmine yet.

**Comment by matcracker** [comment]
Nice work! :D

**Comment by Exxarion** [comment]
Update is now on pocketmine. Enjoy :D

http://forums.pocketmine.net/plugins/worldgm.844/update?update=1988
