### ISSUE TITLE
Console error when player join in the game

### ISSUE THREAD

**Issue by matcracker** [Exxarion/WorldGM#7]
08:19:46 [CRITICAL] Could not pass event pocketmine\event\player\PlayerRespawnEvent to WorldGM v4: Non-static method pocketmine\Server::getDefaultGamemode() should not be called statically on WorldGM\PlayerEventListener
08:19:46 [NOTICE] RuntimeException: "Non-static method pocketmine\Server::getDefaultGamemode() should not be called statically" (E_STRICT) in "/WorldGM_v4.phar/src/WorldGM/Utilities" at line 11

**Comment by Exxarion** [comment]
Fixed in v4.1

https://github.com/Exxarion/WorldGM/releases/tag/v4.1

**Comment by matcracker** [comment]
Good! Thank You :)
