### ISSUE TITLE
teleporting between worlds doesn't enforce gamemode

### ISSUE THREAD

**Issue by primmer** [Exxarion/WorldGM#8]
here's my other active plugins ManyWorlds v1.3.0

I'm using head with your crash fix in 6.0. As others have reported on the forum, say you have two worlds:
cworld (creative)
sworld (survival)

in server.properties i have 
level-name=sworld
gamemode=0

wgm set 0 sworld
wgm set 1 cworld

when starting in sworld, the default world on the server, i'm in creative if i then use 
/mw tp cworld
I am in cworld in survival mode. 
wgm check
player is in gamemode Survival while in world cworld
client immediately crashes.
start the client, it starts up and it's in creative
wgm check
player is in gamemode Creative while in world cworld

Expect no crashes and inventory reset (but not lost).

extra question: what is the intended way for users to switch worlds? is this mod assuming the users are using the ManyWorlds tp command? Adding tp info to the mod docs would clarify this, since it doesn't appear this mod is useful without ManyWorlds or something similar.

**Comment by Exxarion** [comment]
As stated after setting worlds, you need to run /stop in order for changes to go into effect. There are a good amount of bugs supplied in 6.0, and I will be happy to fix them in 6.1 (or 7.0, depending on the amount of changes)

**Comment by primmer** [comment]
I appreciate the effort to provide this functionality to the game.

Sorry. I left out of my report that I do stop and start the server after doing a wgm set command.

So It appears this issue is  a 'showstopper' bug and the plugin shouldn't be promoted as working on the plugins site, so save others wasted time trying it out. I haven't seen any cases on the forums where users are reporting that the current version works.

In fact, I've managed to get my client into a state where after teleporting to a world that is has a wgm setting on it (say cworld), the client immediately crashes. No log info server side to indicate why, simply a disconnect. The only way to get the server working for that user again is either uninstall wgm or to quickly TP the user in the console back to the primary survival world (sworld) before the server recognizes the client as disconnected. 

This type of bug makes me think it should not be listed as working in the plugin repository.

**Comment by Exxarion** [comment]
The crashing is not my problem, but Mojang's. I have said numerous times that crashing is Mojangs fault that needs to get fixed.

WorldGM 6.1 has been released. Try using it and see if it works (it should)

**Comment by primmer** [comment]
Ok. You may have said this many times, however, this very important and obvious issue is not on the main page of your plugin and is very surprising to users. This lack of recognition leads people to assume the cause is your software. I suggest the first thing you say on your plugin page is "this plugin will crash the client with no explanation when the user tries to switch to worlds that have a gamemode set". 

I've decided it's a deal breaker and assume others will too.

As I mentioned in my initial issue report, I have been using the code in '6.1' https://github.com/Exxarion/WorldGM/commit/d3dec671e3ad1913a04dd1f881d67a40588238a3. Your last 3 changes on april 8 appear to be non-functional.

I tested several hours with it last night and my report is based on that code. It is not working, even given the client side crashes are a known issue.

**Comment by Exxarion** [comment]
I shall attempt to fix this problem. Thanks for reporting!
